'use client';
import {QueryClient,QueryClientProvider,useQuery} from '@tanstack/react-query';
import dynamic from 'next/dynamic';import {useEffect,useMemo,useState} from 'react';
import {Activity,ArrowDownToLine,ArrowUpRight,BarChart3,BookOpen,ChevronRight,Database,Globe2,Layers3,Menu,Moon,Search,Sun,X} from 'lucide-react';
import {Button} from '../components/button';import DataTable from '../components/table';import {csv} from '../lib/analytics.mjs';
const Chart=dynamic(()=>import('../components/chart'),{ssr:false,loading:()=> <div className="skeleton chart"/>});
const GeographyMap=dynamic(()=>import('../components/map'),{ssr:false});
const client=new QueryClient({defaultOptions:{queries:{retry:1,staleTime:60000}}});
const API=process.env.NEXT_PUBLIC_API_URL??'http://localhost:8000';
type Row=Record<string,unknown>;type Response={status:string;data:Row[];total?:number;note?:string};
async function request(path:string):Promise<Response>{const r=await fetch(`${API}/api/v1/${path}`);if(!r.ok)throw Error(`API returned ${r.status}. Check the service and source ingestion.`);return r.json()}
const modules=['National overview','Economy explorer','Inflation explorer','Trade intelligence','Population explorer','Pakistan map','Agriculture','Labour market','Energy intelligence','Data catalog','Data quality','Models'];
const endpoint:Record<string,string>={'Trade intelligence':'trade','Population explorer':'population','Agriculture':'agriculture','Labour market':'labour','Energy intelligence':'energy','Data catalog':'catalog','Data quality':'quality','Models':'forecast'};
const descriptions:Record<string,string>={'National overview':'A connected view of Pakistan’s public statistics. Every observation links to its original source.','Economy explorer':'Compare historical indicators with their units, frequencies and coverage intact.','Inflation explorer':'Inspect price indicators and their changes over time. Index levels and inflation rates are distinct measures.','Trade intelligence':'Explore official trade observations. Partner and commodity rankings appear only where the source supports them.','Population explorer':'Compare census observations at their published geographic level.','Pakistan map':'Explore published geographic statistics without inferring district values from national indicators.','Agriculture':'Explore official cultivated area, production and yield with consistent units.','Labour market':'Understand published participation and employment indicators.','Energy intelligence':'Explore official generation, distribution and electricity performance indicators.','Data catalog':'Inspect source coverage, ingestion history and usage conditions.','Data quality':'Inspect the engineering evidence behind the analytical warehouse.','Models':'Review measured model evaluations and experimental forecasts.'};
function download(rows:Row[]){const url=URL.createObjectURL(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='pakistan-data.csv';a.click();URL.revokeObjectURL(url)}
function Empty({title,detail}:{title:string;detail:string}){return <div className="empty"><Database size={34}/><h3>{title}</h3><p>{detail}</p><code>python scripts/ingest.py --help</code></div>}
function Workspace(){const [active,setActive]=useState(modules[0]);const [dark,setDark]=useState(false);const [menu,setMenu]=useState(false);const [indicator,setIndicator]=useState('');const [compare,setCompare]=useState('');const [transform,setTransform]=useState('raw');const [start,setStart]=useState('');const [end,setEnd]=useState('');const [geography,setGeography]=useState('Pakistan');const [page,setPage]=useState(0);const [search,setSearch]=useState('');
useEffect(()=>{const theme=localStorage.getItem('pdp-theme');setDark(theme==='dark')},[]);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';localStorage.setItem('pdp-theme',dark?'dark':'light')},[dark]);
const indicators=useQuery({queryKey:['indicators'],queryFn:()=>request('economy/indicators')});const catalog=useQuery({queryKey:['catalog'],queryFn:()=>request('catalog')});const geo=useQuery({queryKey:['geography'],queryFn:()=>request('geography')});
const available=(indicators.data?.data??[]).filter(r=>active!=='Inflation explorer'||/inflation|cpi|price/i.test(String(r.indicator)));
useEffect(()=>{if(available.length&&!available.some(r=>r.indicator===indicator))setIndicator(String(available[0].indicator))},[indicators.data,active,indicator]);
const params=new URLSearchParams({indicator,geography,transform,limit:'500',offset:'0'});if(start)params.set('start',start);if(end)params.set('end',end);
const timeseries=useQuery({queryKey:['series',indicator,geography,transform,start,end],queryFn:()=>request(`economy/timeseries?${params}`),enabled:!!indicator});
const compareSeries=useQuery({queryKey:['compare',compare,geography,transform,start,end],queryFn:()=>request(`economy/timeseries?${new URLSearchParams({...Object.fromEntries(params),indicator:compare})}`),enabled:!!compare});
const domainPath=endpoint[active];const domain=useQuery({queryKey:['domain',domainPath,page],queryFn:()=>request(`${domainPath}?limit=50&offset=${page*50}`),enabled:!!domainPath});
const rows=(domain.data?.data??[]).filter(r=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
const series=useMemo(()=>[{name:indicator,rows:(timeseries.data?.data??[]).filter(r=>(!start||String(r.period)>=start)&&(!end||String(r.period)<=end)).map(r=>({period:String(r.period),value:r.value==null?null:Number(r.value)}))},...(compare?[{name:compare,rows:(compareSeries.data?.data??[]).map(r=>({period:String(r.period),value:r.value==null?null:Number(r.value)}))}]:[])],[timeseries.data,compareSeries.data,indicator,compare,start,end]);
const meta=available.find(r=>r.indicator===indicator);const isExplorer=['Economy explorer','Inflation explorer'].includes(active);const allError=indicators.error;
const boundaries=process.env.NEXT_PUBLIC_BOUNDARY_URL??'';
return <div className="shell"><a href="#content" className="skip">Skip to content</a><aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span className="brand-mark"><Layers3 size={23}/></span><div>Pakistan<span>DATA PLATFORM</span></div><button className="mobile close" onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button></div><div className="nav-label">PUBLIC DATA INTELLIGENCE</div><nav>{modules.map((name,i)=><button key={name} className={active===name?'nav-item selected':'nav-item'} onClick={()=>{setActive(name);setPage(0);setSearch('');setMenu(false)}}>{i===5?<Globe2 size={17}/>:i>8?<Database size={17}/>:<BarChart3 size={17}/>}<span>{name}</span>{active===name&&<ChevronRight size={15}/>}</button>)}</nav><div className="sidebar-foot"><span className="status-dot"/>Source-backed analytics<p>Open-source · Pakistan</p><a href="https://github.com/Salman-41/pakistan-data-platform" target="_blank" rel="noreferrer">Project repository <ArrowUpRight size={14}/></a></div></aside><div className="workspace"><header className="topbar"><button className="mobile" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button><div className="breadcrumb">Pakistan <ChevronRight size={13}/> Intelligence workspace</div><div className="topbar-actions"><span className="source-tag">Official sources</span><button onClick={()=>setDark(!dark)} aria-label={dark?'Use light theme':'Use dark theme'}>{dark?<Sun size={18}/>:<Moon size={18}/>}</button></div></header><main id="content"><div className="heading"><div><div className="eyebrow">PAKISTAN / {active.toUpperCase()}</div><h1>{active}</h1><p>{descriptions[active]}</p></div><Button className="secondary" onClick={()=>download(isExplorer?timeseries.data?.data??[]:rows)} disabled={!(isExplorer?timeseries.data?.data?.length:rows.length)}><ArrowDownToLine size={16}/> Export CSV</Button></div>{allError&&<div className="alert" role="alert"><Activity size={18}/><div><strong>Data service unavailable</strong><p>{(allError as Error).message} Start the API to load official observations.</p></div><button onClick={()=>indicators.refetch()}>Retry</button></div>}
{active==='National overview'&&<><div className="metric-grid">{[{label:'Published indicators',value:indicators.data?.data.length},{label:'Source datasets',value:catalog.data?.data.length},{label:'Observed geographies',value:geo.data?.data.length},{label:'Platform evidence',value:allError?'Offline':'Source-linked'}].map(m=><div className="metric" key={m.label}><span>{m.label}</span><strong>{m.value??'—'}</strong><small>{m.value===undefined?'Waiting for the data service':'From current ingested warehouse'}</small></div>)}</div><div className="overview-grid"><section className="panel"><div className="panel-title"><div><h2>Economic observatory</h2><p>Published indicator coverage</p></div><span className="badge">Historical data</span></div>{indicators.isLoading?<div className="skeleton tall"/>:available.length?<DataTable rows={available}/>:<Empty title="Your observatory starts with real data" detail="No official observations are loaded yet. Run an ingestion adapter to build the catalog; the platform will display the resulting coverage here."/>}</section><section className="panel narrative"><div className="eyebrow">ENGINEERED FOR TRACEABILITY</div><h2>From public releases to useful evidence.</h2><p>Explore source observations, check quality and compare trends without losing their context.</p>{['Source attribution on observations','Geographic and unit consistency','Measured model validation'].map(t=><div className="principle" key={t}><span className="status-dot"/>{t}</div>)}<Button onClick={()=>setActive('Data catalog')}>Explore data catalog <ArrowUpRight size={16}/></Button></section></div></>}
{isExplorer&&<section className="panel"><div className="filters"><label>Indicator<select value={indicator} onChange={e=>setIndicator(e.target.value)}><option value="">Select published indicator</option>{available.map((r,i)=><option key={i} value={String(r.indicator)}>{String(r.indicator)}</option>)}</select></label><label>Compare<select value={compare} onChange={e=>setCompare(e.target.value)}><option value="">No comparison</option>{available.map((r,i)=><option key={i} value={String(r.indicator)}>{String(r.indicator)}</option>)}</select></label><label>Transformation<select value={transform} onChange={e=>setTransform(e.target.value)}><option value="raw">Original values</option><option value="index">Index: first value = 100</option><option value="pct_change">Period change (%)</option><option value="rolling_mean">Rolling mean</option></select></label><label>From<input type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>To<input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><div className="panel-title"><div><h2>{indicator||'Select an indicator'}</h2><p>{meta?`${meta.unit} · ${meta.frequency} · ${meta.geography}`:'Published units and frequency appear with the data'}</p></div></div>{timeseries.error?<Empty title="Query could not be completed" detail={(timeseries.error as Error).message}/>:timeseries.isFetching?<div className="skeleton chart"/>:series[0].rows.length?<><Chart series={series}/><p className="footnote">Comparisons preserve their original units unless you choose an index. Correlation does not establish causation.</p><DataTable rows={timeseries.data?.data??[]}/></>:<Empty title="No observations in this selection" detail="Choose an ingested indicator and a covered period. No values are interpolated or fabricated."/>}</section>}
{active==='Pakistan map'&&<section className="panel"><div className="filters"><label>Published geography<select value={geography} onChange={e=>setGeography(e.target.value)}><option>Pakistan</option>{(geo.data?.data??[]).filter(r=>r.geography!=='Pakistan').map((r,i)=><option key={i}>{String(r.geography)}</option>)}</select></label><div className="map-note">Only geographic levels published in the data are selectable.</div></div>{boundaries?<GeographyMap url={boundaries}/>:<Empty title="Verified district boundaries are not configured" detail="Configure NEXT_PUBLIC_BOUNDARY_URL with a legally reusable GeoJSON source. National observations are never painted as district-level statistics."/>}<h2>{geography}: available observations</h2>{indicators.data?.data.filter(r=>r.geography===geography).length?<DataTable rows={indicators.data.data.filter(r=>r.geography===geography)}/>:<p className="footnote">No observations at this geographic level are currently loaded.</p>}</section>}
{domainPath&&<section className="panel"><div className="panel-title"><div><h2>{active==='Data quality'?'Pipeline quality evidence':active==='Data catalog'?'Dataset registry':active==='Models'?'Forecast artifacts':'Published observations'}</h2><p>{domain.data?.note??'Rows reflect available source coverage.'}</p></div><label className="search"><Search size={16}/><input aria-label="Search loaded rows" placeholder="Search loaded rows" value={search} onChange={e=>setSearch(e.target.value)}/></label></div>{domain.isLoading?<div className="skeleton tall"/>:domain.error?<Empty title="Service unavailable" detail={(domain.error as Error).message}/>:rows.length?<><DataTable rows={rows}/><div className="pagination"><span>{domain.data?.total??rows.length} available records</span><button disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>Page {page+1}</span><button disabled={rows.length<50} onClick={()=>setPage(page+1)}>Next</button></div></>:<Empty title={active==='Models'?'No evaluated model artifacts yet':'No published data loaded for this module'} detail={active==='Models'?'Train and validate on sufficiently long authentic histories. Metrics and forecasts appear after a successful measured run.':'This module is ready for its source adapter. Check the catalog for coverage and ingestion blockers.'}/>}</section>}
<footer><span>Pakistan Data Platform</span><span>Public evidence. Reproducible analysis.</span><a href={`${API}/docs`} target="_blank" rel="noreferrer"><BookOpen size={14}/> API reference</a></footer></main></div></div>}
export default function Home(){return <QueryClientProvider client={client}><Workspace/></QueryClientProvider>}
