'use client';
import {useState} from 'react';
import dynamic from 'next/dynamic';
import {ArrowUpRight,Database,CheckCircle2,Clock3,TrendingUp} from 'lucide-react';
import DataTable from './table';
const Chart=dynamic(()=>import('./chart'),{ssr:false});
type Row=Record<string,unknown>;
const num=(v:unknown)=>Number(v??0).toLocaleString(undefined,{maximumFractionDigits:2});
const label=(v:unknown)=>String(v??'').replaceAll('_',' ');
function Stats({items}:{items:{label:string;value:unknown;note:string}[]}){return <div className="metric-grid">{items.map(i=><div className="metric" key={i.label}><span>{i.label}</span><strong>{typeof i.value==='number'?num(i.value):String(i.value??'—')}</strong><small>{i.note}</small></div>)}</div>}
const plans:Record<string,{source:string;url:string;description:string;measures:string[]}>={
'Trade intelligence':{source:'Pakistan Bureau of Statistics',url:'https://www.pbs.gov.pk/',description:'Follow exports, imports and the composition of Pakistan’s external trade.',measures:['Exports by commodity','Imports by commodity','Trade balance','Trading partners']},
'Agriculture':{source:'Ministry of National Food Security & Research',url:'https://mnfsr.gov.pk/',description:'Understand crop production, land use and the productivity of major crops.',measures:['Crop production','Cultivated area','Yield per hectare','Provincial coverage']},
'Labour market':{source:'Pakistan Bureau of Statistics',url:'https://www.pbs.gov.pk/',description:'Explore employment, participation and differences across published demographic groups.',measures:['Participation rate','Employment','Unemployment','Gender breakdown']},
'Energy intelligence':{source:'National Electric Power Regulatory Authority',url:'https://nepra.org.pk/',description:'Explore electricity generation, capacity and sector performance.',measures:['Installed capacity','Generation mix','Electricity output','Distribution performance']}};
export default function Dashboard({active,rows,catalog,navigate}:{active:string;rows:Row[];catalog:Row[];navigate:(tab:string)=>void}){
 const [populationMetric,setPopulationMetric]=useState('population');
 if(plans[active]&&!rows.length){const p=plans[active];return <><section className="domain-intro panel"><div className="eyebrow">COVERAGE ROADMAP</div><h2>{p.description}</h2><p className="footnote">This domain has no ingested observations yet. Its statistics will become available after a source publication has been acquired and validated.</p><span className="badge"><Clock3 size={13}/> Awaiting source ingestion</span></section><div className="opportunity-grid">{p.measures.map((m,i)=><section className="panel opportunity" key={m}><span className="opportunity-number">0{i+1}</span><h2>{m}</h2><p>Coverage pending</p><div className="coverage-track"><span/></div><small>No validated series in the current warehouse</small></section>)}</div><section className="panel source-strip"><div><h2>Start with the published source</h2><p>{p.source} · source acquisition pending</p></div><a href={p.url} target="_blank" rel="noreferrer">Visit publisher <ArrowUpRight size={16}/></a><button onClick={()=>navigate('Data catalog')}>View available datasets →</button></section></>}
 if(active==='Data catalog')return <><Stats items={[{label:'Published datasets',value:rows.length,note:'Successfully ingested sources'},{label:'Accepted observations',value:rows.reduce((s,r)=>s+Number(r.processed_rows??0),0),note:'Rows recorded by ingestion manifests'},{label:'Publishers',value:new Set(rows.map(r=>r.source)).size,note:'Distinct source organizations'},{label:'Traceability',value:'Source-linked',note:'Original publication on every dataset'}]}/><div className="dataset-grid">{rows.map((r,i)=><article className="panel dataset-card" key={String(r.ingestion_id??i)}><div className="panel-title"><Database size={24}/><span className="badge">{label(r.ingestion_status)}</span></div><div className="eyebrow">{String(r.source)}</div><h2>{String(r.dataset_version??'Published dataset')}</h2><p>{String(r.time_period)} · {String(r.geographic_level)} coverage</p><div className="dataset-facts"><div><strong>{num(r.processed_rows)}</strong><span>observations</span></div><div><strong>{num(r.quality_score)}%</strong><span>quality score</span></div></div><p className="rights-note">{String(r.license??'Usage terms not recorded')}</p><a href={String(r.source_url)} target="_blank" rel="noreferrer">Open original publication <ArrowUpRight size={14}/></a></article>)}</div></>;
 if(active==='Data quality'){const total=rows.reduce((s,r)=>s+Number(r.raw_rows??0),0);const rejected=rows.reduce((s,r)=>s+Number(r.rejected_rows??0),0);return <><Stats items={[{label:'Acceptance rate',value:total?`${num((total-rejected)/total*100)}%`:'—',note:'Accepted / raw rows'},{label:'Rejected rows',value:rejected,note:'Failed validation'},{label:'Duplicates detected',value:rows.reduce((s,r)=>s+Number(r.duplicates??0),0),note:'Across ingestion batches'},{label:'Missing values',value:rows.reduce((s,r)=>s+Number(r.missing_values??0),0),note:'Recorded by source adapters'}]}/><section className="panel"><div className="panel-title"><div><div className="eyebrow">VALIDATION REPORT</div><h2>Quality by source publication</h2></div><CheckCircle2 color="var(--accent)"/></div>{rows.map((r,i)=><div className="quality-row" key={i}><div><strong>{String(r.dataset_version)}</strong><span>{num(r.processed_rows)} accepted · {num(r.rejected_rows)} rejected</span></div><div className="quality-meter"><span style={{width:`${Math.min(100,Math.max(0,Number(r.quality_score??0)))}%`}}/></div><strong>{num(r.quality_score)}%</strong></div>)}</section><section className="panel audit-panel"><h2>Ingestion audit</h2><DataTable rows={rows.map(r=>({publication:r.dataset_version,completed:r.completed_at,accepted:r.processed_rows,rejected:r.rejected_rows,duplicates:r.duplicates,revisions:r.revisions}))}/></section></>}
 if(active==='Population explorer'){const latest=rows.filter(r=>String(r.period).startsWith('2023'));const populations=latest.filter(r=>r.indicator==='population');const ranking=latest.filter(r=>r.indicator===populationMetric).sort((a,b)=>Number(b.value)-Number(a.value));return <><Stats items={[{label:'Covered population',value:populations.reduce((s,r)=>s+Number(r.value),0),note:'Sum of covered KP districts · 2023'},{label:'District coverage',value:populations.length,note:'KP only; not all Pakistan'},{label:'Census comparison',value:'2017 → 2023',note:'Published district observations'},{label:'Published measures',value:new Set(latest.map(r=>r.indicator)).size,note:'Population and characteristics'}]}/><div className="dashboard-split"><section className="panel"><div className="panel-title"><div><div className="eyebrow">DISTRICT COMPARISON</div><h2>KP district rankings</h2></div><select aria-label="District ranking metric" className="dashboard-select" value={populationMetric} onChange={e=>setPopulationMetric(e.target.value)}>{[...new Set(latest.map(r=>String(r.indicator)))].map(m=><option key={m} value={m}>{label(m)}</option>)}</select></div><div className="ranking-list">{ranking.slice(0,12).map((r,i)=><div className="rank-row" key={String(r.geography)}><span className="rank-position">{String(i+1).padStart(2,'0')}</span><div><span>{String(r.geography)}</span><div className="rank-track"><span style={{width:`${Number(r.value)/Math.max(1,...ranking.map(x=>Number(x.value)))*100}%`}}/></div></div><strong>{num(r.value)}</strong></div>)}</div><p className="footnote">{label(ranking[0]?.unit)} · census 2023</p></section><section className="panel"><div className="eyebrow">CENSUS CHANGE</div><h2>Population growth by district</h2><p className="footnote">Published annual growth rate · 2023 census</p><DataTable rows={latest.filter(r=>r.indicator==='population_growth_annual').sort((a,b)=>Number(b.value)-Number(a.value)).map(r=>({district:r.geography,annual_growth_percent:r.value}))}/></section></div><section className="panel audit-panel"><h2>District observations</h2><DataTable rows={rows}/></section></>}
 if(active==='Models'){const model=rows[0];if(!model)return <section className="panel"><h2>No evaluated models available</h2><p className="footnote">Model evaluations require a sufficiently long validated history.</p></section>;const metrics=model.metrics as Record<string,Row>;const forecast=(model.forecast??[]) as Row[];return <><Stats items={[{label:'Selected model',value:label(model.selected_model),note:'Exploratory model selection'},{label:'Training observations',value:model.training_rows,note:'Chronological training window'},{label:'Holdout observations',value:model.holdout_rows,note:`Beginning ${model.holdout_start}`},{label:'Selected model MAE',value:Number(metrics?.[String(model.selected_model)]?.mae??0),note:'CPI index points · holdout'}]}/><div className="dashboard-split"><section className="panel"><div className="panel-title"><div><div className="eyebrow">EXPERIMENTAL OUTLOOK</div><h2>National CPI forecast</h2></div><span className="badge"><TrendingUp size={12}/> Model estimates</span></div><Chart series={[{name:'Forecast · index points',rows:forecast.map(r=>({period:String(r.period),value:Number(r.value)}))}]}/></section><section className="panel"><div className="eyebrow">MODEL COMPARISON</div><h2>Chronological holdout results</h2><DataTable rows={Object.entries(metrics??{}).map(([name,m])=>({model:label(name),mae:Number(m.mae).toFixed(2),rmse:Number(m.rmse).toFixed(2)}))}/><p className="footnote">Lower MAE and RMSE indicate smaller errors, in CPI index points.</p></section></div><section className="panel audit-panel"><h2>Interpret these estimates carefully</h2>{((model.limitations??[]) as string[]).map(t=><p className="footnote" key={t}>{t}</p>)}</section></>}
 return <section className="panel"><h2>Published observations</h2><DataTable rows={rows}/><p className="footnote">{catalog.length} source datasets in the current catalog.</p></section>;
}
