'use client';
import {useState,useMemo} from 'react';
import dynamic from 'next/dynamic';
import {ArrowUpRight,Search} from 'lucide-react';
import {Kpi,ChartCard} from './national-dashboard';
import DataTable from './table';
import {history,title,unitLabel,points,latest,formatValue,type Observation,type Dictionary} from '../lib/data';
const Visual=dynamic(()=>import('./visual'),{ssr:false,loading:()=> <div className="skeleton" style={{height:290}}/>});
const config:Record<string,{domain:string;default:string;kpis:string[];compare?:string;secondary:string;breakdown:string[];note:string}>={
 Economy:{domain:'economy',default:'gdp_current_usd',kpis:['gdp_current_usd','gdp_per_capita_usd','gdp_growth','remittances_usd'],secondary:'gdp_growth',breakdown:['investment_share'],note:'Current-dollar series measure nominal values. Growth rates use the publisher’s inflation-adjusted GDP methodology.'},
 Inflation:{domain:'inflation',default:'cpi_national',kpis:['cpi_national','cpi_urban','cpi_rural','inflation_annual'],compare:'cpi_urban',secondary:'inflation_annual',breakdown:[],note:'PBS publishes monthly index levels. World Bank annual CPI inflation is a separate measure and frequency.'},
 Trade:{domain:'trade',default:'exports_usd',compare:'imports_usd',kpis:['exports_usd','imports_usd','merchandise_exports_usd','trade_share'],secondary:'trade_share',breakdown:['exports_share','imports_share'],note:'National goods and services totals. Merchandise-only totals use a different coverage definition; partner and commodity breakdowns are not loaded.'},
 Population:{domain:'population',default:'population_total',kpis:['population_total','population_growth','urban_population_share_wdi','fertility_rate'],secondary:'population_growth',breakdown:['population_under_15_share','population_over_65_share','female_population_share'],note:'World Bank demographic estimates and PBS census counts are different series. District values below come from the census publications.'},
 Agriculture:{domain:'agriculture',default:'cereal_production',kpis:['agriculture_value_added_share','cereal_production','cereal_yield','agricultural_land_share'],secondary:'cereal_yield',breakdown:['agricultural_land_share','arable_land_share'],note:'National agricultural indicators. Cereal yields are kilograms per hectare; crop-specific provincial production is not yet loaded.'},
 Labour:{domain:'labour',default:'unemployment_rate_modelled',kpis:['unemployment_rate_modelled','youth_unemployment_modelled','labour_participation_modelled','female_labour_participation_modelled'],secondary:'labour_participation_modelled',breakdown:['female_labour_participation_modelled','male_labour_participation_modelled'],note:'ILO modelled estimates distributed by the World Bank. Participation uses population aged 15+; unemployment uses the labour force denominator.'},
 Energy:{domain:'energy',default:'electricity_access',compare:'rural_electricity_access',kpis:['electricity_access','rural_electricity_access','clean_cooking_access','renewable_energy_share'],secondary:'renewable_energy_share',breakdown:['rural_electricity_access','urban_electricity_access'],note:'National energy access and consumption statistics. Renewable consumption includes all final energy and does not represent electricity generation mix.'},
 Health:{domain:'health',default:'life_expectancy',kpis:['life_expectancy','under_five_mortality','health_expenditure_share','basic_water_access'],secondary:'under_five_mortality',breakdown:['basic_water_access','basic_sanitation_access','measles_immunization'],note:'National health and service access indicators. Mortality rates are deaths per 1,000 live births; immunization measures eligible children.'},
 Education:{domain:'education',default:'adult_literacy',compare:'female_adult_literacy',kpis:['adult_literacy','female_adult_literacy','primary_enrollment_gross','education_expenditure_share'],secondary:'education_expenditure_share',breakdown:['primary_enrollment_gross','secondary_enrollment_gross','tertiary_enrollment_gross'],note:'Gross enrollment ratios can exceed 100%. Literacy is measured for ages 15+; missing survey years remain missing.'},
 Environment:{domain:'environment',default:'forest_area_share',kpis:['forest_area_share','forest_area','freshwater_withdrawals','pm25_exposure'],secondary:'pm25_exposure',breakdown:['agriculture_water_withdrawals','freshwater_withdrawals'],note:'Environmental measures have different units and publication years. Water withdrawal ratios can exceed 100% of internal resources.'},
 Digital:{domain:'digital',default:'internet_access',kpis:['internet_access','mobile_subscriptions','fixed_broadband_subscriptions','secure_internet_servers'],secondary:'mobile_subscriptions',breakdown:[],note:'Subscriptions count connections, not unique people. Mobile subscriptions per 100 people can exceed 100.'}
};
function Districts({rows}:{rows:Observation[]}){const [province,setProvince]=useState('all');const [search,setSearch]=useState('');const districtRows=rows.filter(r=>r.dataset.startsWith('pbs_census')&&r.geography!=='Pakistan'&&(r.dataset.endsWith('_districts')||r.dataset==='pbs_census_2023_kp'));const datasets=[...new Set(districtRows.map(r=>r.dataset))];const selected=districtRows.filter(r=>r.indicator==='population'&&r.period.startsWith('2023')&&(province==='all'||r.dataset===province)&&r.geography.toLowerCase().includes(search.toLowerCase()));const ranked=selected.sort((a,b)=>b.value-a.value);return <section className="panel bi-district-panel"><div className="panel-title"><div><h2>District population · Census 2023</h2><p>{selected.length} published districts in the current selection · PBS</p></div><div className="district-controls"><select aria-label="Census province" value={province} onChange={e=>setProvince(e.target.value)}><option value="all">All loaded provinces</option>{datasets.map(d=><option key={d} value={d}>{d.replace('pbs_census_2023_','').replace('_districts','').toUpperCase()}</option>)}</select><label className="search"><Search size={14}/><input placeholder="Find a district" aria-label="Find a district" value={search} onChange={e=>setSearch(e.target.value)}/></label></div></div><div className="bi-board-row equal-board-row"><Visual kind="bar" categories={ranked.slice(0,10).map(r=>({name:r.geography,value:r.value/1e6}))} label="Ten most populous districts in the selection" unit="million people" height={360}/><div><DataTable rows={ranked.map(r=>({district:r.geography,population:formatValue(r.value,'',false),year:2023,source_url:r.source_url}))}/></div></div><p className="footnote">Census district counts reflect published boundaries. National World Bank estimates are not allocated to districts.</p></section>}
export default function SectorDashboard({active,rows,metadata}:{active:string;rows:Observation[];metadata:Dictionary}){const c=config[active];const [selected,setSelected]=useState(c.default);const [comparison,setComparison]=useState(c.compare??'');const [detail,setDetail]=useState(false);
 const candidates=[...new Set(rows.filter(r=>r.geography==='Pakistan'&&(metadata[r.indicator]?.domain===c.domain||(active==='Inflation'&&r.indicator==='inflation_annual'))).map(r=>r.indicator))];const primary=candidates.includes(selected)?selected:candidates[0]??selected;const meta=metadata[primary];const selectedRows=history(rows,primary);const unit=selectedRows[0]?.unit??meta?.unit??'';const divisor=unit==='current_usd'?1e9:unit==='persons'?1e6:unit==='tonnes'?1e6:1;const displayUnit=unit==='current_usd'?'US$ bn':unit==='persons'?'Million people':unit==='tonnes'?'Million tonnes':unitLabel(unit);const matching=candidates.filter(key=>key!==primary&&metadata[key]?.unit===unit&&history(rows,key)[0]?.frequency===selectedRows[0]?.frequency);const compare=matching.includes(comparison)?comparison:'';
 const chartSeries=useMemo(()=>[{name:title(primary,metadata),rows:points(rows,primary,divisor)},...(compare?[{name:title(compare,metadata),rows:points(rows,compare,divisor)}]:[])],[rows,primary,compare,metadata,divisor]);
 const secondary=history(rows,c.secondary);const categories=c.breakdown.map(key=>({key,row:latest(rows,key)})).filter(x=>x.row).map(x=>({name:`${title(x.key,metadata)} · ${x.row!.period.slice(0,4)}`,value:x.row!.value}));
 return <><div className="bi-kpi-grid sector-kpis">{c.kpis.map(key=><Kpi key={key} rows={rows} indicator={key} metadata={metadata}/>)}</div><div className="bi-board-row main-board-row"><ChartCard title="Explore the history" subtitle={`${displayUnit} · ${selectedRows[0]?.frequency??'published frequency'} · national`} tag={active}><div className="bi-local-filters"><label>Indicator<select value={primary} onChange={e=>{setSelected(e.target.value);setComparison('')}}>{candidates.map(key=><option key={key} value={key}>{title(key,metadata)}</option>)}</select></label><label>Compare in the same units<select value={compare} onChange={e=>setComparison(e.target.value)}><option value="">No comparison</option>{matching.map(key=><option key={key} value={key}>{title(key,metadata)}</option>)}</select></label></div><Visual series={chartSeries} unit={divisor!==1?displayUnit:''} label={`${active} selected indicator histories`} height={310}/><div className="indicator-description"><p>{meta?.definition??c.note}</p>{meta?.source_url&&<a href={meta.source_url} target="_blank" rel="noreferrer">View definition and publication<ArrowUpRight size={13}/></a>}</div></ChartCard><ChartCard title={title(c.secondary,metadata)} subtitle={`${unitLabel(secondary[0]?.unit??'')} · annual`} footnote="Observed values only; no gaps are filled."><Visual series={[{name:title(c.secondary,metadata),rows:points(rows,c.secondary)}]} label={`${active} secondary history`} height={265}/><p className="footnote">{c.note}</p></ChartCard></div>{categories.length>0&&<ChartCard title={`${active} in focus`} subtitle="Latest available values · each label includes its observation year" footnote="Compare definitions and denominators before interpreting these measures."><Visual kind="bar" categories={categories} label={`${active} related published measures`} height={Math.max(200,categories.length*65)} /></ChartCard>}{active==='Population'&&<Districts rows={rows}/>}<section className="panel bi-observation-panel"><div className="panel-title"><div><h2>Published observations</h2><p>{selectedRows.length} source observations · {title(primary,metadata)}</p></div><button className="text-button" onClick={()=>setDetail(!detail)}>{detail?'Hide table':'Show data table'}</button></div>{detail&&<DataTable rows={selectedRows.map(r=>({year:r.period.slice(0,r.frequency==='monthly'?7:4),value:formatValue(r.value,'',false),unit:unitLabel(r.unit),publisher:metadata[r.indicator]?.source,source_url:r.source_url}))}/>}</section></>;
}
